## NumPy

In [ ]:
Why do we use NumPy when Python already has Lists?

A Python list is a general-purpose container. It can store different types:

data = [10, "hello", 3.14, True]

NumPy arrays are designed specifically for numerical/scientific computation.

import numpy as np

numbers = np.array([1, 2, 3, 4, 5])

NumPy provides:

Faster numerical operations
Vectorized computation
Multidimensional arrays
Broadcasting
Mathematical functions
Better memory efficiency for homogeneous numerical data

In [3]:
#numpy
import numpy as np

x = np.array([1,2,3,4,5])
result = x*2
print(result)

[ 2  4  6  8 10]

In [4]:
# In case of list
x = [1,2,3,4,5]
result = x*2
print(result)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

Vectorization

It allows operations to be performed on entire arrays rather than manually writing Python loops.

Instead of:

result = []

for value in x:
    result.append(value * 2)

we can simply write:

result = x * 2

Python list * 2
        ↓
Repeats the list

NumPy array * 2
        ↓
Multiplies every element by 2

"NumPy is designed for efficient numerical computation. Unlike Python lists, NumPy arrays support vectorized operations, multidimensional arrays, broadcasting, and efficient mathematical operations, making them much more suitable for machine learning and scientific computing."

In [8]:
#axis
data = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print(data.ndim)
print(data.shape)
#2rows,3 columns

2
(2, 3)

In [14]:
# axis=0 (means row wise operation)
print(data.sum(axis=0))

print()
# axis =1 (means column wise opeartion)
print(data.sum(axis=1))

[50 70 90]

[ 60 150]

In [15]:
# size tells us the total number of elements.

arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print(arr.size)

6

In [26]:
# Creating NumPy Arrays

print(np.zeros(5))
print()
# 2D
print(np.zeros((2,3))) # 2rows,3 cols
print()
print(np.ones(5))
print()
print(np.ones((2,3)))

[0. 0. 0. 0. 0.]

[[0. 0. 0.]
 [0. 0. 0.]]

[1. 1. 1. 1. 1.]

[[1. 1. 1.]
 [1. 1. 1.]]

In [28]:
# np.arrange():Creates evenly spaced values based on a step

print(np.arange(1,10))
print()

# with specified step
print(np.arange(1,10,2))  # 2 is step size

[1 2 3 4 5 6 7 8 9]

[1 3 5 7 9]

In [29]:
#np.linspace() : Creates a specified number of evenly spaced values between two endpoints.

print(np.linspace(0, 10, 5))  # 5 specifying the no. of values/points we want

# arange() vs linspace()
# arange :You specify the step:

np.arange(0, 10, 2)

# linspace :You specify the number of values:

np.linspace(0, 10, 5)

# arange → step size
# linspace → number of points

[ 0.   2.5  5.   7.5 10. ]

In [37]:
# indexing:
arr = np.array([10, 20, 30, 40, 50])
print(arr[0])
print(arr[3])
print(arr[-1])

print()
# 2d indexing:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print(arr[0,2]) # zeroth row's 2nd element(starts from 0)
print(arr[1,1]) # first row's 1st element

10
40
50

30
50

In [44]:
#NumPy Slicing
arr = np.array([10, 20, 30, 40, 50])
print(arr[1:4]) # starts from 1 to till 4th element(The ending index is excluded.)

print()
# 2d slicing:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(arr[:2])  # first 2 rows
print()
print(arr[:,:2]) # all rows 2 columns

print()
print(arr[:,-1])

[20 30 40]

[[10 20 30]
 [40 50 60]]

[[10 20]
 [40 50]
 [70 80]]

[30 60 90]

In [50]:
# Boolean Masking
arr = np.array([10, 20, 30, 40, 50])
print(arr[arr>30])

print()
ages = np.array([15, 25, 35, 45, 60])
print(ages[ages>18])

[40 50]

[25 35 45 60]

In [51]:
# Arithmetic Operations
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])

# Addition:

print(x + y)

#Multiplication:

print(x * y)

#Division:

print(y / x)

[11 22 33]
[10 40 90]
[10. 10. 10.]

In [54]:
# Broadcasting:Broadcasting allows NumPy to perform operations between arrays of compatible shapes.
# Broadcasting is NumPy's mechanism for performing arithmetic operations on arrays with compatible but different shapes by logically expanding the smaller array without necessarily creating explicit copies.

arr = np.array([10, 20, 30])

print(arr + 5)

# Conceptually:

# [10 20 30]
# +
# [ 5  5  5]
print()
arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

x = np.array([1, 2, 3])

print(arr+x)

[15 25 35]

[[11 22 33]
 [41 52 63]]

In [59]:
#Aggregation Functions
# np.sum(arr)
# np.mean(arr)
# np.median(arr)
# np.min(arr)
# np.max(arr)
# np.std(arr)
# np.var(arr)


arr = np.array([10, 20, 30, 40, 50])

print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))

30.0
30.0
14.142135623730951
200.0

In [64]:
#np.where() :Very useful for conditional transformations.
marks = np.array([35, 80, 45, 90])

# We want:
# Pass if >= 40
# Fail otherwise

res = np.where(
    marks>40,
    "pass",
    "fail"
)
print(res)

['fail' 'pass' 'pass' 'pass']

In [66]:
#np.concatenate()
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.concatenate([a, b])

#For 2D arrays, the axis matters.

array([1, 2, 3, 4, 5, 6])

In [68]:
#vstack() and hstack()

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
# Vertical stacking
print(np.vstack([a, b]))
print()

#horizontal stacking
print(np.hstack([a,b]))

[[1 2 3]
 [4 5 6]]

[1 2 3 4 5 6]

In [71]:
#Reshaping

arr = np.array([1, 2, 3, 4, 5, 6])
print(arr.reshape(2,3))

print(arr.reshape(6,1))
#Important Rule of reshape()

# The total number of elements must remain the same.

[[1 2 3]
 [4 5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]

Valid:

(2, 3)
(3, 2)
(1, 6)
(6, 1)

Invalid:

(2, 4)

because:

2 × 4 = 8

but we only have 6 elements.

In [73]:
#reshape(-1, 1)

x = np.array([10, 20, 30, 40])

print(x.reshape(-1,1)) #One column, determine the number of rows.
print()

print(x.reshape(1,-1))#One row, determine the number of columns.

[[10]
 [20]
 [30]
 [40]]

[[10 20 30 40]]

Why Is This Important in ML?

You may see errors such as:

Expected 2D array, got 1D array instead

For example:

model.predict([10])

may not have the shape expected by the estimator.

You may need:

np.array([10]).reshape(1, -1)

which produces:

[[10]]

Shape:

(1, 1)

That's:

one sample, one feature.

In [75]:
# flatten()

arr = np.array([
    [1, 2],
    [3, 4]
])

arr.flatten()

array([1, 2, 3, 4])

# COnditions:
With NumPy arrays, use:

&
|
~

rather than Python's:

and
or
not

In [79]:
# np.select() for Multiple Conditions
# uppose we want:

# Salary < 40000       → Low
# 40000–70000          → Medium
# > 70000              → High


salary = np.array([30000, 50000, 80000, 120000])

conditions = [
    salary < 40000,
    salary <= 70000,
    salary > 70000
]

choices = [
    "Low",
    "Medium",
    "High"
]

result = np.select(conditions, choices)
print(result)

['Low' 'Medium' 'High' 'High']

## Pandas

The two most important Pandas structures are:

Series

DataFrame

In [92]:
#A Series is essentially a one-dimensional labeled array.
import pandas as pd
from IPython.display import display
data = pd.Series([25,34,25])
print(data)
print()
# # series with defined indexes:
data_1 = pd.Series([25,34,25],
                  index=["Monika","Ritesh","Manvik"])
print(data_1)
print()
print(data_1["Monika"])

0    25
1    34
2    25
dtype: int64

Monika    25
Ritesh    34
Manvik    25
dtype: int64

25

In [88]:
#A DataFrame is a two-dimensional labeled table.
data = {
    "Name": ["Rahul", "Priya", "Monika"],
    "Age": [25, 30, 35],
    "Salary": [50000, 60000, 80000]
}

df = pd.DataFrame(data)

print(df)

     Name  Age  Salary
0   Rahul   25   50000
1   Priya   30   60000
2  Monika   35   80000

In [97]:
display(df["Age"]) # usually 1 dim(series)
print("dimension:",df["Age"].ndim)
display(df[["Age"]]) #returns a DataFrame.
print("dimension:",df[["Age"]].ndim)

0    25
1    30
2    35
Name: Age, dtype: int64

dimension: 1

   Age
0   25
1   30
2   35

dimension: 2

In [98]:
#Reading a CSV File
data_2 = pd.read_csv(r"C:\Users\Monika Dogra\Desktop\data\diabetes_2.csv")

display("Shape:", data_2.shape)

data_2.head()

'Shape:'

(768, 9)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [ ]:
#Reading Other File Types
pd.read_excel()
pd.read_json()
pd.read_sql()

In [101]:
# things to do or observe after reading a file:
df.head()
df.shape
df.info()
df.describe()
df.isnull().sum()
df.duplicated().sum()
df.columns

What is the difference between info() and describe()?

Answer:

"info() gives structural information about the DataFrame, including data types and non-null counts, while describe() provides statistical summary information for numerical columns."

In [102]:
# Checking Missing Values
misising  = df.isnull().sum()

# isna() vs isnull() : These are essentially equivalent in Pandas.Both identify missing values.

In [ ]:
# Percentage of Missing Values
missing_percentage = (
    df.isnull().mean() * 100
)

print(missing_percentage)

In [ ]:
#Selecting a Single Column
age = df["Age"] #returns a Series.
age = df[["Age"]]# returns a dataframe

In [128]:
# Selecting Rows with loc :loc is label-based indexing.
display(df.head())
display(df.loc[0])   # series
display(df.loc[[0]])
display(df.loc[0,"Age"])
display(df.loc[0:4]) #Selects rows from label 0 through 4.
display(df.loc[0:4,["Age"]])  
display(df.loc[0:4, ["Age", "Salary"]])

     Name  Age  Salary
0   Rahul   25   50000
1   Priya   30   60000
2  Monika   35   80000

Name      Rahul
Age          25
Salary    50000
Name: 0, dtype: object

    Name  Age  Salary
0  Rahul   25   50000

25

     Name  Age  Salary
0   Rahul   25   50000
1   Priya   30   60000
2  Monika   35   80000

   Age
0   25
1   30
2   35

   Age  Salary
0   25   50000
1   30   60000
2   35   80000

In [135]:
#Filtering with loc
display(df.loc[df["Age"]>20])

display(df.loc[
    df["Age"] > 30,
    ["Age", "Salary"]
])

     Name  Age  Salary
0   Rahul   25   50000
1   Priya   30   60000
2  Monika   35   80000

   Age  Salary
2   35   80000

In [140]:
#iloc :iloc is position-based indexing.
display(df.iloc[[0]])  #gets the first row.
display(df.loc[[0]])

    Name  Age  Salary
0  Rahul   25   50000

    Name  Age  Salary
0  Rahul   25   50000

In [146]:
#iloc with Rows and Columns
display(df.iloc[0,1])
display(df.iloc[[0,1]])

display(df.loc[0:1])
display(df.loc[[0,1]])

25

    Name  Age  Salary
0  Rahul   25   50000
1  Priya   30   60000

    Name  Age  Salary
0  Rahul   25   50000
1  Priya   30   60000

    Name  Age  Salary
0  Rahul   25   50000
1  Priya   30   60000

In [151]:
#iloc Slicing
display(df.iloc[0:3,0:2])
# display(df.loc[0:3,0:2])# is an error

     Name  Age
0   Rahul   25
1   Priya   30
2  Monika   35

loc	                                     iloc
Label-based	                             Position-based
Uses row/column labels	                 Uses integer positions
End label generally included             End position excluded
in slicing	   
Can use Boolean conditions	             Can use integer positions

In [153]:
# suppose:
df.index = [10, 20, 30, 40]
# now
display(df.loc[20]) #Give me the row whose label is 20.
# and
display(df.iloc[1]) #Give me the second row.

In [158]:
# Filtering DataFrame
display(df["Age"]>30)
df[["Age"]]>30

0    False
1    False
2     True
Name: Age, dtype: bool

     Age
0  False
1  False
2   True

In [155]:
# use this:
df[df["Age"] > 30]

     Name  Age  Salary
2  Monika   35   80000

In [162]:
#Multiple Conditions
#AND

df[(df["Age"]>30) &
 (df["Salary"]>50000)]

     Name  Age  Salary
2  Monika   35   80000

In [163]:
#Or
df[(df["Age"]>30) |
 (df["Salary"]>50000)]

     Name  Age  Salary
1   Priya   30   60000
2  Monika   35   80000

In [168]:
#isin()
# Suppose you want only employees from:

# Pune
# Mumbai
# Delhi
df = pd.DataFrame({
    "Name": ["Rahul", "Priya", "Monika", "Amit"],
    "City": ["Delhi", "Pune", "Mumbai", "Delhi"]
})

display(df[df["City"].isin(["Pune", "Mumbai", "Delhi"])])

     Name    City
0   Rahul   Delhi
1   Priya    Pune
2  Monika  Mumbai
3    Amit   Delhi

In [172]:
df["City"].isin(["Pune", "Mumbai", "Delhi"])

0    True
1    True
2    True
3    True
Name: City, dtype: bool

In [ ]:
# Converting Data Types
df["Age"] =df["Age"].astype(float)

#for dates:

df["Date"] = pd.to_datetime(df["date"])

In [ ]:
# duplicates
df.duplicated().sum()
# remove duplicates
df = df.drop_duplicates()
#You can also specify columns:
df.drop_duplicates(subset=["col_name"])

In [ ]:
# misiing values:
df.isnull().sum()
# drop missing values:
df.dropna()
# fill missing values:
df["Age"] = df["Age"].fillna(df["Age"].Median())

# categorical values:
df["City"] =df["City"].fillna(df["City"].Mode()[0])

In [ ]:
# Groupby:
#We want average salary by city:
df.groupby("City")["Salary"].mean()

df.groupby("City")["Salary"].agg(["mean","min","max","count"])
#This gives several statistics at once.

In [ ]:
# groupby multiple cols:
# Average salary for each City + JobRole combination.

df.groupby(["City","JobRole"])["Salary"].mean()

In [182]:
# sorting
# Name	Age	Salary
# 0	Rahul	25	50000
# 1	Priya	30	60000
# 2	Monika	35	80000


data = pd.DataFrame(data={
    "Name":["Monika","Rahul","Priya"],
    "Age" :[23,24,45],
    "Salary":[30000,35000,25000]
})
data

     Name  Age  Salary
0  Monika   23   30000
1   Rahul   24   35000
2   Priya   45   25000

In [185]:
data.sort_values(["Salary"]) #data.sort_values(["Salary"])

     Name  Age  Salary
2   Priya   45   25000
0  Monika   23   30000
1   Rahul   24   35000

In [187]:
# with multiple columns:
data.sort_values(["Salary","Age"],ascending=False)

     Name  Age  Salary
1   Rahul   24   35000
0  Monika   23   30000
2   Priya   45   25000

In [190]:
data_2 = pd.read_csv(r"C:\Users\Monika Dogra\Desktop\data\diabetes_2.csv")
#value_counts()
data_2["Outcome"].value_counts()
# For percentages:
data_2["Outcome"].value_counts(normalize=True)*100

0    65.104167
1    34.895833
Name: Outcome, dtype: float64

In [193]:
#nunique() :Number of unique values:

data["Name"].nunique()

#unique() vs nunique()
display(data["Name"].unique())
display(data["Name"].nunique())

array(['Monika', 'Rahul', 'Priya'], dtype=object)

3

In [199]:
# apply()

#suppose:We want to convert salary into lakhs:
display(data)
data["Salary_lakhs"] = data["Salary"].apply(lambda x: x/100000)
display(data)

     Name  Age  Salary  Salary_lakhs
0  Monika   23   30000          0.30
1   Rahul   24   35000          0.35
2   Priya   45   25000          0.25

     Name  Age  Salary  Salary_lakhs
0  Monika   23   30000          0.30
1   Rahul   24   35000          0.35
2   Priya   45   25000          0.25

In [ ]:
#map() is commonly used on a Series to map values.

mapping = {
    "Male":1,
    "Female":2
}

data["Gender_mapping"] =data["Gender"].map(mapping)
#This is a simple form of categorical transformation.

In [236]:
l = [3,4,5]
res = list(map(lambda x: x**2, l))
res

[9, 16, 25]

        map()	                                         apply()
Primarily used with Series	                 Can work with Series and DataFrame
Element-wise mapping/transformation	         More general
Useful for dictionary mapping	             Useful for custom functions
Often used for category mapping	             Can operate across rows/columns

In [201]:
#concat()
data = pd.DataFrame(data={
    "Name":["Monika","Rahul","Priya"],
    "Age" :[23,24,45],
    "Salary":[30000,35000,25000]
})
data_1 = pd.DataFrame(data ={
    "Name":["Ritesh"],
    "Age":34,
    "Salary":60000
})

In [202]:
pd.concat(
    [data, data_1],
    axis=0
)

     Name  Age  Salary
0  Monika   23   30000
1   Rahul   24   35000
2   Priya   45   25000
0  Ritesh   34   60000

In [203]:
pd.concat(
    [data, data_1],
    axis=1
)

     Name  Age  Salary    Name   Age   Salary
0  Monika   23   30000  Ritesh  34.0  60000.0
1   Rahul   24   35000     NaN   NaN      NaN
2   Priya   45   25000     NaN   NaN      NaN

In [210]:
# Merge:
#Types of merges
# inner
# left
# right
# outer

df_1 = pd.DataFrame(data={
    "Name":["Monika","Rahul","Priya"],
    "Age" :[23,24,45],
    "Salary":[30000,35000,25000]
},index=[1, 2, 3])
df_1.index.name = "Emp_id"

df_2 = pd.DataFrame(data={
    "Name":["Raj","Rohan"],
    "Age": [34,65],
    "Salary": [58000,760000]
},index= [1,2])
df_2.index.name= "Emp_id"

In [211]:
display(df_1)
display(df_2)

          Name  Age  Salary
Emp_id
1       Monika   23   30000
2        Rahul   24   35000
3        Priya   45   25000

         Name  Age  Salary
Emp_id
1         Raj   34   58000
2       Rohan   65  760000

In [216]:
#Inner:Only matching records.
merged_inner = pd.merge(
    df_1,
    df_2,
    on="Emp_id",
    how="inner"
)
display(merged_inner)

        Name_x  Age_x  Salary_x Name_y  Age_y  Salary_y
Emp_id
1       Monika     23     30000    Raj     34     58000
2        Rahul     24     35000  Rohan     65    760000

In [219]:
# Left :Keep everything from left DataFrame.
merged_left = pd.merge(
    df_1,
    df_2,
    on="Emp_id",
    how="left"
)
display(merged_left)

        Name_x  Age_x  Salary_x Name_y  Age_y  Salary_y
Emp_id
1       Monika     23     30000    Raj   34.0   58000.0
2        Rahul     24     35000  Rohan   65.0  760000.0
3        Priya     45     25000    NaN    NaN       NaN

In [220]:
# Right :Keep everything from right DataFrame.
merged_right = pd.merge(
    df_1,
    df_2,
    on="Emp_id",
    how="right"
)
display(merged_right)

        Name_x  Age_x  Salary_x Name_y  Age_y  Salary_y
Emp_id
1       Monika     23     30000    Raj     34     58000
2        Rahul     24     35000  Rohan     65    760000

In [221]:
#Outer:Keep everything from both.
merged_outer = pd.merge(
    df_1,
    df_2,
    on="Emp_id",
    how="outer"
)
display(merged_outer)

        Name_x  Age_x  Salary_x Name_y  Age_y  Salary_y
Emp_id
1       Monika     23     30000    Raj   34.0   58000.0
2        Rahul     24     35000  Rohan   65.0  760000.0
3        Priya     45     25000    NaN    NaN       NaN

merge() vs concat()
concat is :
Stack datasets

df1
df2
 ↓
combined
 
merge is:
Join datasets using a key

df1 ← EmployeeID → df2

concat → stacking
merge  → joining

join() is mainly index-based, while merge() is mainly column/key-based.

join() — mainly works with INDEX

merge() — mainly works with COLUMNS

In [225]:
# join() : is another way to combine DataFrames, often based on their indexes.

df1 = pd.DataFrame({
    "Name": ["Monika", "Rahul", "Priya"],
    "Age": [23, 24, 45]
}, index=[1, 2, 3])

df2 = pd.DataFrame({
    "Salary": [30000, 35000, 25000],
    "City": ["Pune", "Delhi", "Mumbai"]
}, index=[1, 2, 3])

result = df1.join(df2)

display(result)

     Name  Age  Salary    City
1  Monika   23   30000    Pune
2   Rahul   24   35000   Delhi
3   Priya   45   25000  Mumbai

In [229]:
# join() : is another way to combine DataFrames, often based on their indexes. then how will it handles this below:

display(df_1)
display(df_2)
result = df_1.join(
    df_2,
    lsuffix="_df1",
    rsuffix="_df2"
)

print(result)

          Name  Age  Salary
Emp_id
1       Monika   23   30000
2        Rahul   24   35000
3        Priya   45   25000

         Name  Age  Salary
Emp_id
1         Raj   34   58000
2       Rohan   65  760000

       Name_df1  Age_df1  Salary_df1 Name_df2  Age_df2  Salary_df2
Emp_id
1        Monika       23       30000      Raj     34.0     58000.0
2         Rahul       24       35000    Rohan     65.0    760000.0
3         Priya       45       25000      NaN      NaN         NaN

In [230]:
# Keep only the columns you actually need
res = df_1.join(
    df_2[["Salary"]],
    lsuffix="_df1",
    rsuffix="_df2"
    )
print(res)

          Name  Age  Salary_df1  Salary_df2
Emp_id
1       Monika   23       30000     58000.0
2        Rahul   24       35000    760000.0
3        Priya   45       25000         NaN

In [234]:
# left join and right join
#left
res_left = df_1.join(
    df_2,
    how = 'left',
    lsuffix='_df1',
    rsuffix='_df2'
    )
display(res_left)

#right
res_right = df_1.join(
    df_2,
    how = 'right',
    lsuffix='_df1',
    rsuffix='_df2'
    )
display(res_right)

# inner
res_inner =df_1.join(
    df_2,
    how = "inner",
    lsuffix="_df1",
    rsuffix="_df2"
    )
display(res_inner)

#outer
res_outer =df_1.join(
    df_2,
    how = "outer",
    lsuffix="_df1",
    rsuffix="_df2"
    )
display(res_outer)

       Name_df1  Age_df1  Salary_df1 Name_df2  Age_df2  Salary_df2
Emp_id
1        Monika       23       30000      Raj     34.0     58000.0
2         Rahul       24       35000    Rohan     65.0    760000.0
3         Priya       45       25000      NaN      NaN         NaN

       Name_df1  Age_df1  Salary_df1 Name_df2  Age_df2  Salary_df2
Emp_id
1        Monika       23       30000      Raj       34       58000
2         Rahul       24       35000    Rohan       65      760000

       Name_df1  Age_df1  Salary_df1 Name_df2  Age_df2  Salary_df2
Emp_id
1        Monika       23       30000      Raj       34       58000
2         Rahul       24       35000    Rohan       65      760000

       Name_df1  Age_df1  Salary_df1 Name_df2  Age_df2  Salary_df2
Emp_id
1        Monika       23       30000      Raj     34.0     58000.0
2         Rahul       24       35000    Rohan     65.0    760000.0
3         Priya       45       25000      NaN      NaN         NaN

## A Strong Pandas EDA Sequence

In [ ]:
import pandas as pd

df = pd.read_csv("data.csv")

print(df.head())
print(df.shape)
print(df.columns)
print(df.info())
print(df.describe())

print(df.isna().sum())
print(df.duplicated().sum())

print(df.dtypes)

In [ ]:
Then investigate:

df["target"].value_counts()

and categorical variables:

df["City"].value_counts()

Then relationships:

df.groupby("City")["Salary"].mean()

Data quality
Are there duplicates?
Are there missing values?
Are there impossible values?
Are datatypes correct?
Are there outliers?
Target
Is the target balanced?
Is there leakage?
Is the target correctly defined?
Features
Numerical?
Categorical?
High cardinality?
Highly skewed?
Constant?
Near-constant?
Pipeline
Can preprocessing be reproduced?
Can the exact same transformation be applied during inference?

## Feature engineering:
Feature engineering is the process of converting raw data into useful input features that a machine-learning model can learn from effectively.

For example, suppose we have:

Date of Birth: 15-05-1995

A model generally shouldn't directly use this raw date.

We can create:

Age = 31

1. Numerical Features
We need to check:
Is it continuous?
Is it discrete?
Is it heavily skewed?
Does it contain outliers?
Does it need scaling?
Does zero have a meaningful interpretation?

2. Categorical/Encoding Categorical Variables:
1. Label Encoding
2. Ordinal Encoding
3. One-Hot Encoding
4. Frequency Encoding
5. Target Encoding

### Encoding

In [ ]:
#Label Encoding:
#say suppose we have gender :
# Gender
# ------
# Male
# Female
# Female
# Male

from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

df["Gender"] = encoder.fit_transform(df["Gender"])

# will results into :
# Male   → 1
# Female → 0

# but never apply Label encoding on ordering.like:
# City:
# Pune
# Mumbai
# Delhi

# which will get converted into:
# Pune   → 0
# Mumbai → 1
# Delhi  → 2
# which means: Delhi > Mumbai > Pune

# which has no meaningful relationship.

# Therefore, LabelEncoder is generally not the right choice for nominal input features.

In [ ]:
#Ordinal Encoding:

from sklearn.preprocessing import OrdinalEncoder
# High School → 1
# Bachelor     → 2
# Master       → 3
# PhD          → 4

# This is appropriate because the ordering contains information.

In [ ]:
#One-Hot Encoding
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(
    handle_unknown="ignore"
)

# One-hot encoding creates:

# Pune | Mumbai | Delhi
# ---------------------
# 1    | 0      | 0
# 0    | 1      | 0
# 0    | 0      | 1

# Why handle_unknown="ignore"?:

# Suppose during training we saw:

# Pune
# Mumbai
# Delhi

# but during production we receive:

# Bangalore

# Without proper handling, the encoder can raise an error.
# handle_unknown="ignore"

# the unseen category is handled safely.

# This is an important production interview point.

### Scaling:
Common scalers:

StandardScaler

MinMaxScaler

RobustScaler

1.StandardScaler:
Formula:

z = (x - mean) / standard deviation

After scaling, the feature typically has:

mean ≈ 0
std  ≈ 

*****Important*****

Do:

fit_transform → training data
transform      → test data

NOT:

scaler.fit_transform(X_test)

because that leaks information from the test set.

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

2.MinMaxScaler

Transforms values to a chosen range, commonly:

0 to 1

Formula:

x_scaled =
(x - min) / (max - min)

In [ ]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

3.RobustScaler:

Useful when the dataset contains significant outliers.

It uses:

Median
IQR

rather than mean and standard deviation.

This makes it less sensitive to extreme values.

In [ ]:
from sklearn.preprocessing import RobustScaler

Which Models Need Scaling?

This is a very common interview question.

Usually scaling is important for:
Logistic Regression
Linear Regression (especially when optimization/regularization is involved)
SVM
KNN
K-Means
Neural Networks
PCA

Why?

Because these methods depend on:

distances
magnitudes
gradients
regularization
Usually scaling is NOT required for:
Decision Tree
Random Forest
Gradient Boosting
XGBoost
LightGBM

because tree-based models split based on feature thresholds.

Skewed Features

Suppose salary is:

30000
35000
40000
45000
50000
10000000

The distribution is highly right-skewed.

This can cause problems for some models and statistical procedures.

A common solution is a transformation.

1. Log Transformation

A common transformation is:

import numpy as np

df["Salary_log"] = np.log1p(df["Salary"])

Why log1p()?

Because:

log1p(x) = log(1 + x)

and it safely handles zero values.

Example:

Salary = 0

np.log(0)

is problematic.

But:

np.log1p(0)

returns 
0

When Should We Use Log Transformation?

Common situations:

Income
Salary
House prices
Transaction amounts
Population
Counts

especially when there is a long right tail.

But don't blindly log-transform every numerical column.

First inspect:

df["Salary"].skew()

and the distribution.

### Binning

In [ ]:
# Binning converts continuous values into categories.

# Suppose:

# Age
# 22
# 27
# 35
# 48
# 65

# We might create:

# 18-30 → Young
# 31-50 → Middle
# 51+   → Senior

# Using:

df["Age_Group"] = pd.cut(
    df["Age"],
    bins=[0, 30, 50, 100],
    labels=["Young", "Middle", "Senior"]
)


# Experience
# Skills_Rating

# We can create:

df["Experience_Skill"] = (
    df["Experience"] *
    df["Skills_Rating"]
)

# Income
# Debt

# Create:

df["Debt_Income_Ratio"] = (
    df["Debt"] / df["Income"]
)

### Feature Selection

Feature selection decides:

Which features should we keep?

Methods include:

Correlation
Mutual Information
Chi-square
ANOVA
RFE
L1 regularization
Tree-based importance

In [ ]:
# The Best Production Solution: Pipeline

# Instead of manually doing:

# Imputation
# ↓
# Encoding
# ↓
# Scaling
# ↓
# Model

# we can create a pipeline.

# Example:

from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler()),
    ("model", LogisticRegression())
])

# Then:

pipeline.fit(X_train, y_train)

# and:

predictions = pipeline.predict(X_test)
# This is much safer and easier to deploy.

### Mixed Numerical + Categorical Data

In [ ]:
# Suppose:

# Age              → numerical
# Salary           → numerical
# Experience       → numerical
# City             → categorical
# Education        → categorical

# We can use:

from sklearn.compose import ColumnTransformer

numeric_features = [
    "Age",
    "Salary",
    "Experience"
]

categorical_features = [
    "City",
    "Education"
]
# numeric pipeline
numeric_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

# Categorical pipeline:

categorical_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(
        handle_unknown="ignore"
    ))
])

# Combine:

preprocessor = ColumnTransformer([
    ("num", numeric_pipeline, numeric_features),
    ("cat", categorical_pipeline, categorical_features)
])

# Then model:

model_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("model", LogisticRegression(max_iter=1000))
])

# This is the kind of structure you should be comfortable explaining in an ML interview.

ColumnTransformer:
Instead of preprocessing each column separately, you can use ColumnTransformer
What happens internally?

It applies:

Age       ──────> StandardScaler ───┐
Salary    ──────> StandardScaler ───┤
                                     ├──> Combined output
Gender    ──────> OneHotEncoder ────┘

we don't have to manually do:

X["Age"] = scaler.fit_transform(...)
X["Salary"] = scaler.fit_transform(...)
X["Gender"] = encoder.fit_transform(...)